apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: sample-app
spec:
  selector:
    matchLabels:
      app: sample-app
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      serviceAccountName: sample-app
      containers:
        - name: sample-app
          image: us-central1-docker.pkg.dev/pw-asm-gke-prj-1/samplesample-app:latest
          env:
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "sample-app"
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.1.0
          command:
            - "--private-ip"
            - "-log_debug_stdout"
            - "-instances=pw-asm-gke-prj-1:us-central1:sample-app-mysql-db-8cf33039=tcp:3306"
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
