apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: sample-app
spec:
  selector:
    matchLabels:
      app: sample-app
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      serviceAccountName: sample-app
      containers:
        - name: sample-app
          image: us-central1-docker.pkg.dev/pw-asm-gke-prj-1/sample/sample-app:latest
          env:
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "sample-app"
            - name: DB_USER
              value: "sample-app@pw-asm-gke-prj-1.iam.gserviceaccount.com"
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.1.0
          args:
            - "--private-ip"
            - "--structured-logs"
            - "--port=3306"
            - "pw-asm-gke-prj-1:us-central1:sample-app-mysql-db-8cf33039"
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
