apiVersion: v1
data:
  config: |
    nonMasqueradeCIDRs:
      - 10.0.0.0/28 # Control Plane IP Range
      - 10.114.0.0/22 # Pods IP Range
      - 10.115.0.0/24 # Service Ip Range
    masqLinkLocal: false
    resyncInterval: 60s
kind: ConfigMap
metadata:
  name: ip-masq-agent
  namespace: kube-system